# Generated by Django 3.2.25 on 2024-06-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_account_microfrontend_url_field_from_SiteConfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='usd_rmb_exchage_rate',
            field=models.FloatField(blank=True, default=7.3, help_text='Exchange rate for USD to RMB', null=True, verbose_name='USD to RMB exchange rate'),
        ),
    ]
